#!/usr/bin/env python


# wx, pyaudio and pyobjc fucking hate each other
# so don't even import them before sparking each his own thread

# fork wx inside siri
import siri


import filters



from time import sleep

from enums import *



def filter_bullshit(words):
  for word in words:
    # this is fucked. What if I want to use a word like 'left' on its own?
    if word not in bullshit:
      yield word

def fix_symbols(xs):
    for x in xs:
      if x in prefixes:
        yield x + "-" + xs.next()
      else:
        yield x




def do_click(arguments):
        print "mouse:", arguments
        if "right" in arguments:
            button = mouse.RIGHT_BUTTON
        elif "middle" in arguments:
            button = mouse.CENTER_BUTTON
        else:
            button = mouse.LEFT_BUTTON
        if "hold" in arguments:
            mouse.toggle(True, button)
        elif "release" in arguments:
            mouse.toggle(False, button)
        else:
            if "double" in arguments:
                double_click(button)
            elif "triple" in arguments:
                triple_click(button)
            else:
                mouse.click(button)

def type_string(s, mod=0):
              for x in s:
		key_tap(unicode(x), mod)


siri_words = ['lowered', 'awaken', 'hired']
def do_actions(acts):
          mod = []
          mods = 0
	  for a in acts:
            print 'action', a
            if isinstance(a, tuple):
		(a, mod_list) = a
                mod1 = reduce(lambda a, b: a | b, mod_list, 0)
            else:
              mod1 = 0

            for k in mod:
              mods |= k

	    if isinstance(a, str):
              type_string(a, long(mods | mod1))
	    elif isinstance(a, int):
              if a in mod_set:
                mods |= a
              else:
		key_tap(long(a), long(mods | mod1))
                sleep(0.1)
            else:
                print "do_actions can't handle", a, "of type", type(a)

def apply_filter(filt, phrase):
  f = filters.filters[filt]
  return f(phrase)

siri_filter=None

def start_siri(filt):
  global siri_filter
  global started_siri
  if started_siri: # shouldn't happen
    return
  started_siri = True

  siri_filter = filt
  siri.pop_mini_editor(filt)

started_siri = False

def finish_siri():
  global started_siri

  if not started_siri:
      return ''
  started_siri = False
  phrase = siri.finish()
  filtered = apply_filter(siri_filter, phrase)
  print 'phrase', phrase, 'filtered', filtered
  sleep(1)
  type_string(filtered)


# In case you want to finish the mini editor and discard the results.
def cancel_siri():
  global started_siri

  if not started_siri:
      return ''
  started_siri = False
  siri.finish()

def do_siri(s):
  global english_mode

  if s in ['lowered', 'hired']:
    start_siri(s)
  elif s == 'awaken':
    if english_mode:
      siri.toggle_siri()
      english_mode = False
    else:
      finish_siri()

def do_modifier(results_list):
  k = results_list[-1]
  if k == 'super':
    k = 'command'
  key_press_seconds(k, 0.5)
  
def do_repeat(numbers):
  if len(numbers) == 0:
    n = 1
  else:
    n = int(''.join(map(number_map.get, numbers)))
  print 'repeat', n, numbers
  for _ in range(n):
    react_full_result(previous_s)


english_mode = False
previous_s = ''

def     do_mouse(edges):
  xres, yres = screen.get_size()
  x = xres / 2
  y = yres / 2
  if 'left' in edges:
    x = 0
  if 'right' in edges:
    x = xres - 1
  if 'top' in edges:
    y = 0
  if 'bottom' in edges:
    y = yres - 1
  mouse.move(x, y) 



def react_full_result(s):
  global english_mode, previous_s

  results_list = s.split()
  print results_list
  if results_list[0] == 'repeat':
    do_repeat(results_list[1:])
    return
  else:
    previous_s = s

  if results_list[0] == 'mouse':
    do_mouse(results_list[1:])
  elif s == 'english':
    to_listen_queue.put(SLEEP)
    siri.toggle_siri()
    english_mode = True
  elif s in siri_words:
    do_siri(s)
  elif len(results_list) == 0:
    return
  elif results_list[-1] == "click":
    do_click(results_list)
  elif results_list[-1] in mod_keys:
    do_modifier(results_list)

  else:
    actions1 = filter_bullshit(results_list)
    actions2 = fix_symbols(actions1)
    actions3 = map(all_map.get, actions2)
    do_actions(actions3)


FULL_RESULT = 1
def react_tokens(tokens):
  try:
    while True:
      token = tokens.get()
      print token
      (result_type, result_string) = token
      if result_type == FULL_RESULT:
          react_full_result(result_string)
  finally:
    keysup()


from multiprocessing import Process, Queue 

tokens = Queue()
to_listen_queue = Queue()

def run_listener(tokens, to_listen_queue):
  import listener
  listener.listen(tokens, to_listen_queue)

def listen_speech():
    process = Process(target=run_listener, args=(tokens, to_listen_queue))
    process.start()

# fork pyaudio
listen_speech()

# main thread can have plat for now
from plat import *

letter_map = {
        "alpha"    : "a",
        "bravo"    : "b",
        "charlie"  : "c",
        "delta"    : "d",
        "echo"     : "e",
        "foxtrot"  : "f",
        "golf"     : "g",
        "hotel"    : "h",
        "india"    : "i",
        "juliet"   : "j",
        "kilo"     : "k",
        "lima"     : "l",
        "mike"     : "m",
        "november" : "n",
        "oscar"    : "o",
        "papa"     : "p",
        "quebec"   : "q",
        "romeo"    : "r",
        "sierra"   : "s",
        "tango"    : "t",
        "uniform"  : "u",
        "victor"   : "v",
        "whiskey"  : "w",
        "x-ray"    : "x",
        "yankee"   : "y",
        "zulu"     : "z",
        } 


number_map = {
  "one" : "1",
  "two" : "2",
  "dual" : "2",
  "dose" : "2",
  "three" : "3",
  "fowers" : "4",
  "four" : "4",
  "fife" : "5",
  "five" : "5",
  "six" : "6",
  "seven" : "7",
  "eight" : "8",
  "octane" : "8",
  "niner" : "9",
  "nine" : "9",
  "zero" : "0",
  "oh" : "0",
  }

symbol_map = {
        "pipe"              : "|",
        "vertical"              : "|",
        "colon"             : ":",
        "semi-colon"        : ";",
        "dot"               : ".",
        "comma"             : ",",
        "dash"              : "-",
        "plus"              : "+",
        "equal"             : "=",
        "slash"             : "/",
        "backslash"         : "\\",
        "question-mark"     : "?",
        "left-bracket"      : "[",
        "right-bracket"     : "]",
        "left-brace"        : "{",
        "right-brace"       : "}",
        "lepper"  : "(",
        "ripen" : ")",
        "left-parenthesis"  : "(",
        "right-parenthesis" : ")",
        "tiled"             : "~",
        "squiggle"           : "~",
        "quote"             : "'",
        "back-quote"        : "`",
        "double-quote"      : "\"",
        "left-angle"        : "<",
        "right-angle"       : ">",
        "bang"              : "!",
        "batty"             : "@",
        "batter"             : "@",
        "hash"              : "#",
        "pound"             : "#",
        "dollars"           : "$",
        "percent"           : "%",
        "carrot"            : "^",
        "cartoon"            : "^",
        "ampersand"         : "&",
        "star"              : "*",
        "underscore"        : "_",
        "space"     : " ",
        "enter"     : key.K_RETURN,
        "return"     : key.K_RETURN,
        # "tabby"     : 48,
        "tabby"     : "\t",
        }

key_map = {
        "delete"    : key.K_BACKSPACE,
        "page-up"   : key.K_PAGEUP,
        "page-down" : key.K_PAGEDOWN,
        "lefty"      : key.K_LEFT,
        "righty"     : key.K_RIGHT,
        "upper"        : key.K_UP,
        "downer"      : key.K_DOWN,
        "escape"    : key.K_ESCAPE
        }

mod_map = {
        "shift"     :  key.MOD_SHIFT ,
        "command"   :  key.MOD_META ,
        "super"   :  key.MOD_META ,
        "control"   :  key.MOD_CONTROL ,
        "alternate" :  key.MOD_ALT ,
        }

mod_set = mod_map.values()
mod_keys = mod_map.keys()

def dict_union(ds):
    r = {}
    for d in ds:
      r.update(d)
    return r

all_map = dict_union([mod_map , key_map , symbol_map ,number_map,  letter_map, mod_map ])

prefixes = set(["double", "semi", "left", "right", "back", "question", "page"])

bullshit = set([ "number",  "key",  "spell",  "symbol" ])

react_tokens(tokens)
# We should never arrive here
print 'An Error occured:'
